# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\"\x1c\n\x0b\x45\x63hoMessage\x12\r\n\x05value\x18\x01 \x01(\t23\n\x0b\x45\x63hoService\x12$\n\x04\x45\x63ho\x12\x0c.EchoMessage\x1a\x0c.EchoMessage\"\x00\x62\x06proto3')
)




_ECHOMESSAGE = _descriptor.Descriptor(
  name='EchoMessage',
  full_name='EchoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='EchoMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=45,
)

DESCRIPTOR.message_types_by_name['EchoMessage'] = _ECHOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EchoMessage = _reflection.GeneratedProtocolMessageType('EchoMessage', (_message.Message,), dict(
  DESCRIPTOR = _ECHOMESSAGE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:EchoMessage)
  ))
_sym_db.RegisterMessage(EchoMessage)



_ECHOSERVICE = _descriptor.ServiceDescriptor(
  name='EchoService',
  full_name='EchoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=47,
  serialized_end=98,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='EchoService.Echo',
    index=0,
    containing_service=None,
    input_type=_ECHOMESSAGE,
    output_type=_ECHOMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHOSERVICE)

DESCRIPTOR.services_by_name['EchoService'] = _ECHOSERVICE

# @@protoc_insertion_point(module_scope)
