<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6a0a0d736572766963652e70726f746f221c0a0b4563686f4d65737361" .
            "6765120d0a0576616c756518012001280932330a0b4563686f5365727669" .
            "636512240a044563686f120c2e4563686f4d6573736167651a0c2e456368" .
            "6f4d6573736167652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

